#! / bin / bash

echo "sakiri"

sleep 1

echo "l            .. ..':;';:l::d0k0ccXMMMMMMMMMMMMMMMMMMMMk.NMXNMMMNXXXXXXXXXX0XXXXXXXXXXXXXXXNWMMMX0WMMMMMMMMNXMMMMMMMMMMMMMMMMM
N.            .  ...'';:;;;dxdkxxloxXMMMMMMMMMMMMMMMMN'kMNXMWWNXXXXXXXXXXXOXXXXXXXXXXXXXXXXXNWMWKXMMMMMMMMMXMMMMMMMMMMMMMMMMM
M0                ........:coodkOO0KdodXMMMMMMMMMMMMW,oMNNWNXXXXXXXXXXXXXKOXXXXXXXXXXXXXXXXXXXXNNKXMMMMMMMMXWMMMMMMMMMMMMMMMM
MMc               ......,,l::odOOkkKXXOcldKMMMMMMMMMo,WWXNXXXXXXX0XXXXXXX00XXXXXXXXXXXXXXXXXXXXXXX0XMMMMMMMWXMMMMMMMMMMMMMMMM
MMK                ......:;';cdcddoOOK0O0kxddXMMMMMK.KWKNXXXXXXX0XXXXXXXXK0XXXXXXXXXXXXXXXXXXXXXXXK0XMMMMMMMNNMMMMMMMMMMMMMMM
MMM;                  ... ..;:;okd. .:loxOWKklokXMW,cMXXXXXXXXXK0XXXXXXXXK0XXXXXXX0XXXXXXXXXXXXXXXXX0KWMMMMMMKWMMMMMMMMMMMMMK
MMMO                    .  ..,:;oo: 'lc:;;c:;:coodo.XWKXXXXXXXXOXXXXXXXXXXOXXXXXXXkXXXXXXXXXXXXXXXXXX0KWMMMMMWKMMMMMMMMMMWx'
MMMW.                   . .....'col,.OMMMMMMWNXK00,,NXKXXXXXXXXOXXXXXXXXXX0XXXXXXXkXXXXXXXXXXXXXXXXXXXK0XWMMMMWKMMMMMMMNl.
MMMM:                       ...'cc::,.0MMMMMMMMMMX.ONXXXXXXXXX0OXXXX0XXXXX0KXXXXXXx0XXXXXXXXXXXKKXXXXXXXKKWMMMMNXMMMMMX.
MMMMx                        .'.;',:;,.XMMMMMMMMMd.WXXXXXXXXXXOKXXXX0XXXXXKOXXXXXXKo0XXXXXXXXXXXXKKXKKXXXXXXMMMMNXMMMMO
MMMMK                        ......''''.XMMMMMMMM:cNXXXXXXXXXXOXXXXX0XXXXXXOXXXXXXXdK00KXXXXXXXXXXK000KKXXXNNNMMMNKMMMWk,..;o
MMMMW.                        ... ...''..KMMMMMMM'kXX0XXXXXXXXkXXXXXOXXXXXXK0XXXXXXOxXXK000XXXXXXXXXXKK000KXWWNNWMWKMMXXMMMMM
MMMMM'                        ... ....,''.KMMMMMW.0XK0XXXXXXXXOXXXXX0KXXXXXXOXXXXXXXoKXXXXK000KXXXXXXXXX00O0KNMMNNNWKWXXMMMMM
MMMMM;                    ;. .  ..  .,;'''.KMMMMX.KXKOXXXXXXXXOKXXXXKOXXXXXXKOXXXXXXOxXXXXXXXX0O00KXXXXXXXXK0OKXNWWNNKKKMMMXM
MMMMM:                    KWo    ..  ....'..KMMMK.XXKOXXXXXXXX00XXXXXOXXXXXXX00XXXXXXdKXXXXXXXXXXX00000KXXXXXXXXXKKKXN0KMMM0M
MMMMMl                   ;MMMO.   .c.c...,,,,XMM0.XXX0XXXXXXXXK0XXXXXK0XXXXXXXOKXXXXX0dXXXXXXXXXXXXXXXXK00000KKXMMMWNX00MMM0M
MMMMMc                   kMMMM0.   k.k0...;;,;NMK.XXXOXXXXXXXXXOXXXXXXOXXXXXXXXOXXXXXXdkOOOOO0000XXXXXXXXXXXXXK0KNNWMMX0MMW0M
MMMMM;                  .WMMMMMK. .od:MWk'',c;,0N.KXX0XXXXXXXXX0XXXXXX00XXXXXXXK0XXXXXKoXXXXXXXXXXXXXXXXXXXXXXXOokkXWMXOMMNxN
MMMMM'                  oMMMMMMMX, :N'NMMWx..;:.x,KXX00XXXXXXXXKOXXXXXKOXXXXXXXXK0XXXXXkxXXXXXXXXXXXXXXXXXXXXXXXXNXx0WXOMMWkK
MMMMX                   XMMMMMMMMWo'MckMMMMWd,',.'kXXX0XXXXXXXXXOXXXXXXO0XXXXXXXXK0XXXXXo0XXXXXXXXXXXXXXXXXXXXXXXXWMNNKkMMWOM
MMMMO                  cWNXXWMMMMMMOXOlMMMMMMNo,, oXXXOKXXXXXXXXXOXXXXXKO0XXXXXXXXK0XXXXKlKXXXXXXXXXXXXXXXXXXXXXXXNMMMNxMMWOM
MMMXNO.                XMMMWKKKKNMMMMNcMMMMMMMMNl..KXXKOXXXXXXXXX0kXXXXX0kKXXXXXXXXXKXXXX0dXXXXXXXXXXXXXXXXXXXXXXXXWMMWxMMMkW
MMX..;l.              cMMMMMMMMWKKKKKXdMMMMMMMMMMX,,0XKk0XXXXXXXXXcoXXXXX0O0XXo:KXXXXXxxxkodKXXXXXXXXXXXXXXKK00OOKXNMMWxMMMxN
MX.                   XMMMMMMMMMMMMMWXxMMMMMMMMMMMK.'0X0kKXXXXXXXX0.;OXXXXKOOXx,xxddodOXXXXXXXKOxdlc;,'....;codO0XXNMMMxMMMxK
x.                   oMMMMMMMMMMMXOooO0MMMMMMMMMMMMckXXXOOXXXXXdXXX0;0kkOKXX0oxdKXXXXX00xl;'..     .';ldOKXXXXXXXXXXWMMxMMMkW
                    .NMMMMMMMNkxdxKc.NWMMMMMMMMMMMMK;XXXXkkXXXXxlkXX0l0XKOOOk0XXXK0kl,.       .ck0XXXXXXXXXXXXXXXXXXNMMxMMMkM
                    xMMMMMKxxkNMMMMx oMMMMMMMMMMMMMMxlXXXKkk0XXOldkkkkxKXXXXXXXXXKdcloc         ,OXXXXXXXXXXXXXXXXXXNMMxWMMkM
                   'WMMXkk0WMMMMMMMK 'MMMMMMMMMMMMMMMooXKOKOdokOOk0XXXXXXXXXXXXXXXXXXXo           :KXXXXXXXXXXXXXXXXXMMdNMMOM
                   xWOk0WMMMMMMMMMMM. NMMMMMMMMMMMMMMWd:xOd;dOXXXXXXXXXXXXXXXXXXXXXXXXo            .OXXXXXXXXXXXXXXXXMMxXMMOW
                   xkXMMMMMMMMMMMMMM: NWXMMMMMMMMMMMMMMk..OdkXXXKKXXXXXXXXXXXXXXXXXXXXO             .0XXXXXXXXXXXXXXXWMk0MMOW
          .:.      KMMMMMMMMMMMMMMMMOoWM0kNMMMMMMMMMMMMMXl.odl'...oXXXXXXXXXXXXXXXXXXXX;           ..cXXXXXXXXXXXXXXXWM0kMMOW
           .k.     0MMMMMMMMMMMMMMMMMMMMMNxd0WMMMMMMMMMMMM0...;. :XXXXXXXXXXXXXXXXXXXXXd    ...  ...,:XXXXXXXXXXXXXXXWMXxMMON
 'dXW0..., ,';     lMMMMMMMMMMMMMMMMMMMMMMMWOxddONMMMMMMMMMl0KOo  xXXXXXXXXXXXXXXXXXXXXK,''.....'';codXXXXXXXXXXXXXXXWMNdMMON
kMMMWXxd',:,cx.    .NMMMMMMMMMMMMMMMMMMMMMMMMMMW0xolcclodXMKoXk0. .KXXXXXXXXXXXXXXXXXXXXx:ooc;:;:clkkkXXXXXXXXXXXXXXXNMWdMMON
MMMMXXOMXlcoxdd     dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKo.XMMcXXkl  lXXXXXXXXXXXXXXXXXXXXXdldkkokkkOdxXXXXXXXXXXXXXXXXNMMdMM0N
MMMKNKWMMM0xOO0.    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMloMMMlOXOO. .KXXXXXXXXXXXXXXXXXXXXXd:0KdKKkd0XXXXXXXXXXXXXXXXXNMMdMM0N
MMW:WKMMMMN0O00l     0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW.KMMMklXXkl''dXXXXXXXXXXXXXXXXXXXXXXKOXKXXXXXXXXXXXXXXXXXXXXXXNMMdWM0N
MMk xMMMMMMW0OOK.    cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0.WMMMX,XXOO:ooKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMMxNMON
MM0OkMMMMMMMW0OOd     NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdcMMMMW,KXXOkdoxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMxXWON
MWxNMMMMMMMMMWKO0;    oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMcOMMMMM:dXX00o:dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMxKWON
MWNOXMMMMMMMMMNKOO.   .WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:NMMMMMd:XXXKXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMk0NON
MKNMKXMMMMMMMMMNKKO    dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdMMMMMM0'XX0OckXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMMM0ONON
MWKNxlWMMMMMMMMMWKXo   .WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0MMMMMMN.0XOdXk0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMMM0kNkN
WMN0koMMMMMMMMMMMN0Nc   xMMMMMMMMMMMMMMMMMMMMMMMMMMMMWoWMMMMMM'kX0:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMKxNkN
KWMWKx0MMMMMMMMMMMNKN'  'WMMMMMMMMMMMMMMMMMMMMMMMMMMMMKcNMMMMMloXK'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMNxNxN
W0XMMNklNMMMMMMMMMMNKX.  xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo;MMMMMk:XX'OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMMMMWdNdX
MMX0NMMNK0XMMMMMMMMMXNO  .WMMMMMMMMMMMMMMMMMMMMMMMMMMMMd,MMMMMX;XXccXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMMWxWdX
MMMWKKMMMMXKKMMMMMMMNXMd  xMMMMMMMMMMMMMMMMMMMMMMMMMMMX.OMMMMMW:XX0'KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMMMMMMxWdX
XXXKXKXKNMMMWKNMMMMMMKWWc 'WMMMMMMMMMMMMMMMMMMMMMMMMMModMMMMMMMcOXXllXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMMMMxWoX
MMMMMNKKxkNMMMNkXMMMMMNMW: 0MMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMxdXXX:lXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMxWdK
MMMMMMMMMKxxNMMMxKMMMMMMMWclMMMMMMMMMMMMMMMMMMMMMMMMXKWMMMMMMMMKcXXXXo:0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMMMMMkNdO
MMMMMMMMMMMW00MMNdMMMMMMMMWkWMMMMMMMMMMMMMMMMMMMMMMMMMdOMMMMMMMW:XXXXX0ldXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMMMMMMMkXxk
MMMMMMMMMMMMMNKK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW'XMMMMMMMlOXXXXXKOodKXXXXXXXXXXXXX0xOkKXXXXXXXXXXXXXXXXXWMMMMMMMMMO0kx
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.KMMMMMMMOcXXXXXKKXOlokXXXXXXXXXXXXk0KXXXXXXXXXXXXXXXXXWMMMMMMMMMMKOOo
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMloMMMMMMMMW;KXXXXX0XXX0ddoxKXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMMMMMMMMMNO0l
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:WMMMMMMMMMxoXXXXX0XXXXKM0ldllkXXXXXXXXXXXXXXXXXXXXXXWMMMMMMMMMMMMWWkKl
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW:MMMMWKkoc;;':lddl,',;oxWNxXO ;ddod0XXXXXXXXXXXXXXXNWMMMMWNX0kxdc,.'oX:
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN.dd:,;cdk0NWMMMMMNXWWNO:llcON.0MMMXkdddodx0KK0Okxdoocc:cccllcOKKclOo;X:
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:'coOWMMMMMMMMMMMMMMXNMMNKW0lc.0MMMMMMMMWKl lllodxk0KXNNWMMMMXkd;0MMMlNc
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc:xXNKNMMMMMMMMMMMMMMMMMXNMMXOXNW0lcxNMMMMMMMMx,XMWXXXWMMMMNNMMMNclx.KMMlOO
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdcdXWMNXMMMMMMMMMMMMMMMMMMMMXWMMONNKXMWOclXMMMMMMMK;dNWXKXXMMMMWN0l,ko. OMMkcK
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWdl0MMXMWKMMMMMNMMMMMMMMMMMMMMMWXMMWOMMWXNMMKclXMMMMMMWo,xNXOOKNMMKc;ckl:c'OMMN,K
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMldMMMNXMXXMMMMWXMMMMMMMNMMMMMNWMXMMMkKWMMNXMMMl.NMMMMMMM0.lXWkkKX:.:;O:::::OMMM;0"

sleep 2
echo ""
echo ""

echo "SELAMAT ULANG TAHUN BEGO"

echo "yah selamat ulang tahun adek di umur yang 19? kan? semoga sehat selalu kedepannya biar ndak sakit terus "

echo "$date"
